spring:
  application:
    name: zipkin-server
  cloud:
    steam:
      kafka:
        binder:
          brokers:
          zNodes:

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: true
    fetch-registry: true

security:
  basic:
    enabled: false

zipkin:
  storage:
    type: cassandra3
    cassandra3:
      keyspace: pluralsite
      contact-points: 127.0.0.1
      username: cassandra
      password: test
      ensure-schema: false
      use-ssl: true
