version: '2'
services:
  cassandra:
    container_name: cassandra
    image: cassandra:3.9
    volumes:
      - /path/of/host/for/cassandra/:/var/lib/cassandra/
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    environment:
      - CASSANDRA_CLUSTER_NAME='cassandra-cluster'
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    restart: always