spring:
  application:
    name: eureka-server

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: false
    fetch-registry: false
