spring:

  application:
    name: zipkin-service-two

  zipkin:
    base-url: http://zipkin-server
    enabled: true

    sleuth:
      sampler:
        probability: 1.0

server:
  port: 9292

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: true
    fetch-registry: true