spring:
  application:
    name: zuul-gateway

server:
  port: 8282

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: true
    fetch-registry: true